# Generated by Django 5.1.6 on 2025-02-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
