# Generated by Django 5.1.6 on 2025-02-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_brand_brand_remove_category_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='brand',
            name='brand',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='detail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
